### ISSUE TITLE
Custom URL YouTube

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FranciscoLaPelicula#10]
Fede, me dice Mariano, nuestro CM, que no necesitamos 500 subscriptores si vos seguís el tutorial que está en este link

Instructivo:
https://support.google.com/youtube/answer/2657968?ref_topic=3024172&hl=es

Andá directamente a la parte dedicada a los Webmasters. Confirmame si ahora sí se puede hacer.

abrazo

**Comment by FAAREIA** [comment]
Lea, pasame la cuenta de gmail asi nos metemos y lo hacemos

**Comment by LeandroBraier** [comment]
Genial. Ahi va:

admin: franciscolapelicula@gmail.com

la password es la misma de deposit photos

Avisame cualquier cosa.

abrazo

**Comment by braulio-evangelisti** [comment]
La dejo como youtube.com/c/Franciscolapelicula o alguna diferente?

**Comment by LeandroBraier** [comment]
Ya te confirmo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Debería ser esta:

youtube.com//franciscolapelicula

Creo que las mayusculas no importan no?

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by braulio-evangelisti** [comment]
Lea, me obliga si o si a agregarle caracteres a la URL, que le agrego?
![image](https://cloud.githubusercontent.com/assets/11272253/8012756/27d569a8-0b9a-11e5-8718-9406b0d196ee.png)

**Comment by LeandroBraier** [comment]
Entonces dame un minuto que consulto.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Probá con esta versión

youtube.com/BergoglioElPapaFrancisco

abrazo

**Comment by braulio-evangelisti** [comment]
Creo que no se puede modificar nada de lo que esta sobre el fondo gris, solo agregar caracteres al final.
Dejame que pruebo si se puede customizar la url de la pagina porque el "Franciscolapelicula" lo toma de la pagina de Google+ por eso la tomó así de entrada.

**Comment by LeandroBraier** [comment]
Fijate si podés cambiarle el nombre en google plus, no hay problema. Lo importante es que la custom url sea o "FranciscoLaPelicula" o "BergoglioElPapaFrancisco"

abrazo

**Comment by braulio-evangelisti** [comment]
Ya esta
YouTube: https://www.youtube.com/Franciscolapelicula
Google+: https://plus.google.com/+Franciscolapelicula <-- página, dentro del perfil

**Comment by LeandroBraier** [comment]
Gracias Braulio!

Por favor agregá los links a Facebook, Twitter y este canal de YoUTube en la web de Francisco, que eso veo que nos quedó pendiente. Tendrían que estar arriba de todo, a la derecha del menú.

abrazo

**Comment by braulio-evangelisti** [comment]
en el menu, a la derecha de todo hay dos botones de facebook y twitter, ahi le agrego el de youtube? o decis a la derecha del ultimo boton de menu (prensa) agrego los 3 iconos?

**Comment by LeandroBraier** [comment]
Pero esos no llevana Facebook y a Twitter, son botones de like y tweet.
Necesito un logito de Facebo, uno de Twitter y uno de YOuTube, como hay en
la página de Río Ancho, que lleven a cada uno de los perfiles.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-08 12:46 GMT-03:00 Braulio Evangelisti notifications@github.com:

**Comment by braulio-evangelisti** [comment]
Si entiendo. Preguntaba mas que nada por el lugar donde situarlos. Fijate ahi que te parece, cuando este ok, lo replico en el resto de las páginas:

http://www.benteveo.tv/_francisco/index.html

**Comment by LeandroBraier** [comment]
Ahí quedó perfecto. Igual consultale a Fede como desplegabamos antes las redes sociales, porque me parece que teníamos otra forma de mostrarlas que con tantas modificaciones se perdió. Hablalo con Fede porfa porque estaba hecho pero por ahora cierro el ticket.

abrazo
