### ISSUE TITLE
Capa semitransparente de posteos de Facebook. DEADLINE: 09/06

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FranciscoLaPelicula#11]
Fede, te paso este ticket como recordatorio para que mañana le subas esta capa de posteos a la página de Francisco la Película. El resto ya quedo todo resuelto con Braulio.

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, ahi lo chequié y está en todas las secciones excepto en Galería que seguro lo sacamos por algo en su momento.

**Comment by LeandroBraier** [comment]
Yo no lo veo en ninguna Fede. Puede ser?

Estoy en Mac Lion y Chrome 43.0.2357.124 64bits.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Voy a iniciar un mac y probar, es raro igual. En chrome PC se ve

2015-06-11 10:11 GMT-03:00 LeandroBraier notifications@github.com:

**Comment by FAAREIA** [comment]
Ya se lo que te esta pasando que lo recordé cuando inicié la mac.
Cuando la altura del navegador es X, esos dos desplegables semi.transparentes de facebook y twitter se ocultan porque simplemente chocarían con el contenido que uno trata de navegar/ver/seleccionar
Cuando el navegador tiene menos de 890px de altura, se ocultan.

**Comment by LeandroBraier** [comment]
No creo. Tengo resolución HD y en la web de Life Of Pi me aparecen bien.
Pongo pantalla completa y en la de Francisco siguen sin aparecer.

http://www.lifeofpimovie.com/

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-11 10:26 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Creo que son HD no alcanza, no recuerdo bien cual era el ancho y alto de un monitor HD, pero chequeate esta página http://whatsmy.browsersize.com/ y fijate que es lo que te dice el valor "Browser window height".
Además la web de life of pi no esta hecha responsiva y tiene solo 2 secciones. El home con el video de fondo en donde los emergentes se muestran siempre y el reparto-equipo en donde los emergentes se solapan con el texto que tiene scroll.

**Comment by LeandroBraier** [comment]
Ok. Te paso la resolución mia Fede. Es esta:

Browser window width:1636Browser window height:847Screen width:1680Screen
height:1050Screen color depth:24

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-12 9:23 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Entonces es eso, como dije antes si el navegador tiene menos de 890px de altura, se ocultan. Vos tenes 847px. Mostrarlos en esa altura implicaría que el usuario esta moviendo el mouse sobre el contenido para seleccionar un texto o hacer un click derecho y la ventana emergente podría aparecerle

**Comment by LeandroBraier** [comment]
Perfecto, Fede. Tiro un BrowserStack para chequear y estamos. Abrazo

**Comment by LeandroBraier** [comment]
Fijate, Fede. Yo no lo veo en ninguna versión (además que no está responsive, no? o al menos eso parece decir BrowserStack)

https://www.browserstack.com/screenshots/a97fa46f6f3abcdbe25f60e5d8f000aed4d2301e

**Comment by FAAREIA** [comment]
Desconozco con que resoluciones prueba browsertack. Responsive está todo.

**Comment by LeandroBraier** [comment]
Pero viste las capturas de Iphone y mobile? No se ve bien el sitio.

Igual no le demos prioridad. Lo reviso y te aviso.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Fede: en base a lo hablado, dejemoslo en la home en cualquier resolución de escritorio. Obviamente mobile no hace falta.

**Comment by braulio-evangelisti** [comment]
Lea ya esta el cambio, ahora en la home los bloques se ven desde 600px de alto para arriba.

Abrazo

**Comment by LeandroBraier** [comment]
Excelente! Ahora sí!

abrazo
