### ISSUE TITLE
Nuevo Logo y nombre de la peli de Francisco 21/07

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FranciscoLaPelicula#12]
Fede, ahora cambió el nombre de la peli otra vez y cambió la estética. Ahora se llama "Francisco, el Padre Jorge". 

El video queda. Solo hay que cambiarle esa estética. Te mandé por mail los archivos vectorizados del logo. 

Implica:

. Home: Cambiar el logo y el nombre de la página en general a Francisco, el Padre Jorge

. Info: Cambiar el título de la peli en la ficha

. Footer general: Nombre de la peli

abrazo

**Comment by LeandroBraier** [comment]
Sería para el martes. abrazo

**Comment by FAAREIA** [comment]
http://www.benteveo.tv/_francisco/info.html
Necesito que me pasen la foto de info o el PSD sino.

**Comment by LeandroBraier** [comment]
Dale, te lo paso.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
![via y riachuelo_back](https://cloud.githubusercontent.com/assets/6719872/8778692/a5ea309a-2ed5-11e5-84a2-471de2d279f9.jpg)

**Comment by FAAREIA** [comment]
La foto no era la de la tapa del DVD?

**Comment by LeandroBraier** [comment]
Ah, yo pensé que decías la del fondo. La del DVD es esta:

http://www.pampafilms.com.ar/Site/images/img_AFICHES_PRODUCCIONES/70_bergoglio.jpg

Igual proximamente va a cambiar.

**Comment by FAAREIA** [comment]
Ok, espero a que cambie entonces. La que me enviaste es la antigua, tiene el nombre viejo.

**Comment by LeandroBraier** [comment]
Claro, pero por ahora dejá ese. abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Gracias por esto Fede! Te aviso cuando tengo el poster posta y la música oficial.

abrazo
