### ISSUE TITLE
Nueva música Francisco La Película. 14/08

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FranciscoLaPelicula#13]
Fede, ya tenemos la música definitiva de la web del Papa.

https://www.wetransfer.com/downloads/ebea712a96f4fcc10802864731c53b5620150810154343/b1ecc0

1) Te sirve o necesitás que te vuelva a pasar el mp4 con la música insertada?

2) Fijate cómo hacen estos tipos para tener esa calidad de imagen o adaptarla a la banda ancha:

http://www.dooplerstudio.com/

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, si deberías pasarme el mp4 con la musica insertada.
Vi el sitio ese, no tiene nada raro. Es un video pesado en un sitio muy liviano, casi no tienen nada más que texto y alguna imagen liviana de fondo.

**Comment by LeandroBraier** [comment]
Pero ese formato de video no lo podemos usar nosotros para tener mejor
calidad de video?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-13 9:31 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Se usan 3 formatos en web, nosotros usamos 2 porque el 3 no hace falta. Uno de esos 2 es el mp4 que los del sitio ese usan. Simplemente es un video pesado, ahora cuando me lo pases, mañana o el lúnes si no llegamos con corralones lo subo pesado asi ves.

**Comment by LeandroBraier** [comment]
Dale, perfecto. Calculo que hoy lo tenemos.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-13 9:37 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
Fede, aquí va el nuevo fondo. Confirmame si te sirve así:

https://www.wetransfer.com/downloads/2d1bf7543eda3693d54cebfe2bdc0dc020150813225313/8982ea9df0ec510c72026fbd9583f4ed20150813225313/cada48

**Comment by LeandroBraier** [comment]
Fede, apenas puedas actualizá esto así ya podemos publicar esta web.

abrazo

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA ! Necesito urgente que subas este video a la web de Francisco de la forma que lo hablamos, para que se vea en la más alta calidad posible.

Confirmame si puede estar para el mediodía.

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
gracias Fede!!! abrazo grande
