### ISSUE TITLE
Subir el Sitio de Francisco al Dominio Oficial

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FranciscoLaPelicula#14]
Fede, tenemos el OK. Lo antes que puedas subí el sitio web al dominio oficial:

franciscolapelicula.com

Consulta: Seguramente nos van a pedir subir una versión en inglés y redirigir el dominio popefrancismovie.com

Avanzá por favor con eso y, cuando tengas listo el sistema, avisame y te paso los textos.

abrazo

**Comment by FAAREIA** [comment]
Ahi ya esta subido Lea.

Lo de la versión en ingles el trabajo consiste en duplicar las secciones, ponerles los textos traducidos y luego vincular las secciones ingles-castellano mediante las banderitas. Lo ideal sería hacerlo cuando nos pasen los textos.

El dominio de "pope...." ya esta delegado a otro lado, necesito que le pongan los DNS de duplika para hacer que popefrancismovie.com vaya a franciscolapelicula.com

#### DNS Duplika
- ns1.duplika.com – 162.159.24.40
- ns2.duplika.com – 162.159.25.235

**Comment by LeandroBraier** [comment]
Entiendo, Fede. Quedó excelente y gracias por todos los datos!!

Voy a consultar como quieren proceder con eso.

abrazo
