### ISSUE TITLE
Cambiar el Afiche de la Peli en Sección INFO

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FranciscoLaPelicula#15]
Si puede ser antes de subir el sitio a producción mejor, pero no es excluyente. Subilo hoy, eso si, porfa.

![afiche100x70a300](https://cloud.githubusercontent.com/assets/6719872/9363002/27094cfe-467a-11e5-8a33-249f7bb310ed.jpg)

abrazo

**Comment by FAAREIA** [comment]
Hecho
