### ISSUE TITLE
Subir Sección Trailer Francisco

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FranciscoLaPelicula#16]
Fede, apenas puedas subí la sección del Trailer con el Trailer final. Ya lo tenemos. Te paso el embed

`<iframe width="560" height="315" src="https://www.youtube.com/embed/RRxQZi11Db0?rel=0" frameborder="0" allowfullscreen></iframe>``

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Excelente Fede! Mil gracias por la velocidad!

abrazo grande
