### ISSUE TITLE
Agregado a sección Prensa

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FranciscoLaPelicula#17]
@FAAREIA necesito que vos o @braulio-evangelisti agreguen estos datos al pie de la sección de prensa.

Francisco Cerdan – in prensa y medios/ press & media
e-mail: info@inprensa.com

Podrá estar para hoy a la noche?

abrazo

**Comment by braulio-evangelisti** [comment]
Ahi arregle con Fede, yo lo hago Lea.

Esto hay que ponerlo en el pie de fondo blanco con el mismo estilo o tendría que estar destacado bajo el formulario?

**Comment by LeandroBraier** [comment]
Gracias Brau! Destacado bajo el formulario.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-09-01 15:07 GMT-03:00 Braulio Evangelisti notifications@github.com:

**Comment by braulio-evangelisti** [comment]
Fijate ahí Lea

Abrazo

**Comment by LeandroBraier** [comment]
Perfecto Brau! Abrazo y gracias

**Comment by LeandroBraier** [comment]
Porfa mañana ponelo por fuera del marco del formulario. Abajo, en tamaño un cuerpo más grande la fuente.

abrazo

**Comment by braulio-evangelisti** [comment]
Fijate ahora Lean

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Brau. Ahora fijate que en el texto en gris no se lee sobre la foto. Ponelo en color blanco con sombra si podes, pero asegurate que se lea tanto en versión web como mobile.

Abrazo

**Comment by braulio-evangelisti** [comment]
Cual texto en gris Lea? En prensa también?

**Comment by LeandroBraier** [comment]
En la versión web está OK, pero en la versión mobile se ve en gris. Mirá:

![screenshot_2015-09-02-08-46-13](https://cloud.githubusercontent.com/assets/6719872/9631345/9f79c560-5156-11e5-827f-615a612945f7.png)

**Comment by braulio-evangelisti** [comment]
Proba de actualizar la pagina en el celu un par de veces a ver si es algo cacheado por favor. 
Tendría que verse centrado y en color blanco en vez de gris.
Voy a chequear el css de todas formas a ver si me falto cambiar algo y te aviso.
Abrazo
