### ISSUE TITLE
Estimación de tiempos para Replicar esta Web para otra película

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FranciscoLaPelicula#18]
@FAAREIA estamos lanzando una nueva peli en Febrero. Cuántas horas te llevaría replicar esta web para una nueva peli? La estructura sería igual pero con contenidos distintos (videos, imagenes, etc)

Llegarías a tenerla para principios de febrero si arrancamos la semana que viene?

abrazo

**Comment by FAAREIA** [comment]
Yo creo que si el sitio es igual y cambian algunos colores y eso no va a haber drama. Copio a brau @braulio-evangelisti

**Comment by braulio-evangelisti** [comment]
Calculo que no habría problemas para llegar a esa fecha Lea. Una vez que esté confirmado todo el contenido final (sea texto, imagenes, videos, colores, fuentes) con 28hs tendría que alcanzar, tal vez menos si no hay que realizar ningún cambio posterior.

**Comment by LeandroBraier** [comment]
Genial chicos!! Gracias!!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-12-30 9:46 GMT-03:00 Braulio Evangelisti notifications@github.com:
