### ISSUE TITLE
Landing Conocé el Set

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FranciscoLaPelicula#4]
Fede, necesito que reemplaces el formulario "Ser parte" por este que te mando aquí.

Título: "Conocé el Set"

Dejanos tus datos para participar por un lugar en la visita al set en nuestro último día de rodaje en Argentina este viernes 27 de febrero.

Los datos de la columna izquierda permanencen siendo los mismos. Los de la columna izquierda cambian. No va el "Subí tu foto" y la pregunta cambia por: "¿Por qué te gustaría visitar el set de rodaje de la peli? 

La foto de fondo sería esta:

https://www.dropbox.com/s/u787z24sljo1i77/0.Homil%C3%ADa_1%20%28Unicode%20Encoding%20Conflict%29.jpg?dl=0

Porfa confirmame cuando la hayas cambiado.

abrazo

**Comment by LeandroBraier** [comment]
Porfa, lo antes posible tener listo esto. Es la prioridad número 1 de hoy.

**Comment by LeandroBraier** [comment]
No te olvides de hacerlo con bloqueo de navegadores anteriores IE8 y que pida javascript habilitado.

abrazo

**Comment by LeandroBraier** [comment]
Porfa subile metada a la página. El título es el metatitulo y el texto "Dejanos tus datos para participar por un lugar en la visita al set en nuestro último día de rodaje en Argentina este viernes 27 de febrero." es la "metadescription". Los key no hacen falta. 

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, ahi subi la página: http://benteveo.tv/_francisco/set-visit.html
Lo del bloqueo a IE8 ahora no hace falta, lo del javascript habilitado ahi lo agrego.

**Comment by FAAREIA** [comment]
Ahi esta listo lo del javascript deshabilitado. Al estar el browser sin javascript, el sitio te redirige a una página de error que dice que lo tenés que habilitar para poder usar el sitio correctamente.

**Comment by FAAREIA** [comment]
Cuando puedas probá el formulario Lea, que ahora que no tiene lo de la foto, hay que ver como va. Toqué un poco el archivo de marce por lo que veamos si lo manda bien.

**Comment by LeandroBraier** [comment]
Hola Fede! Ahi probé el formulario y no funciona. Te paso el texto del
error:

_Warning_: file_get_contents(./respuesta-set-visit.html): failed to open
stream: No such file or directory in
_/home/benteveo/public_html/_francisco/set-visit-email.php_ on line _87_

_Warning_: Cannot modify header information - headers already sent by
(output started at
/home/benteveo/public_html/_francisco/set-visit-email.php:87) in
_/home/benteveo/public_html/_francisco/set-visit-email.php_ on line _114_

También te falta:
1. cambiar el título, que debe ser "Conocé el Set"
2. Cuando pongo en link en Facebook me aparece la metadata pero ninguna
   imagen. Necesitaría que levante la imagen del fondo de la landing, puede
   ser?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Fijate ahora todo lo que me marcaste.
Acordate que en FB: https://developers.facebook.com/tools/debug/og/object/ es el link que me habías pasado en su momento

**Comment by LeandroBraier** [comment]
Ahora funciona bien Fede.

Tenés que cambiar el texto del pop up que aparece luego de enviar el
formulario.

Donde dice: "¡Ya estás participando para #SerParte de Francisco, la
película!" debe decir "¡Ya está participando para #ConocerElSet de
Francisco, la Película"

En el título del mail donde dice "¡Ya estás participando para #SetVisit de
Francisco, la película!" debe decir lo mismo que en el pop up.

Con eso ya estamos.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-02-20 16:06 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ahi esta listo. Fijate ahora y decime cuando haya que subirlo.

Abrazo

**Comment by LeandroBraier** [comment]
Ahora está perfecto, Fede. Subilo ya.

Ya que sumaste los links a redes, que están buenos como los pusiste,
necesitaría que cambies el texto interno de la ventanita. Donde dice:
"Obtené las últimas actualizaciones" debería decir "Seguinos en Facebook" y
"Seguinos en Twitter" en cada caso.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
http://franciscolapelicula.com/

**Comment by LeandroBraier** [comment]
Buenisimo Fede!

Estoy viendo que falta una S y el signo de exclamación de cierre en el pop
up y en el título del mail

"¡Ya estás participando para #SetVisit de Francisco, la película!"
Corregile eso nomás. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Perdón perdón

El texto sería así:

"¡Ya estás participando para #ConocerElSet de Francisco, la película!"

Ese es el texto final.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-02-20 17:14 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

**Comment by LeandroBraier** [comment]
Cuando hagas estas modificaciones, por favor forzale la actualización de la metadata a Facebook como hiciste la otra vez, así cuando inserto el link me aparece con las últimas modificaciones.

abrazo

**Comment by LeandroBraier** [comment]
Fede, recibiste mis últimos pedidos?

Necesito que forces a que Facebook actualice la metadata porfa.

beso

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-02-20 17:15 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

**Comment by FAAREIA** [comment]
Ahi cambié todo Lea, ya levanta bien la imagen y todo.

Abrazo

**Comment by LeandroBraier** [comment]
Fede, necesitaría cambiar la landing actual por un mensaje que diga simplemente "Francisco la película. Sitio en construcción". La foto actual puede quedar por el momento.

**Comment by FAAREIA** [comment]
Ahi esta listo Lea:
http://franciscolapelicula.com/

Abrazo

**Comment by LeandroBraier** [comment]
Perfecto, Fede. Gracias!

**Comment by LeandroBraier** [comment]
Estaba pensando. Mejor en este sitio en construcción sumemosle las ventanitas de Facebook y Twitter, para que la gente pueda ir a algún lado.

**Comment by FAAREIA** [comment]
Hola Lea, ahi lo agregué! Dale F5

Abrazo

**Comment by LeandroBraier** [comment]
Genial Fede. Cómo venís con las webs de Klaukol, Parex y Lanko? Hoy calculo que ya Eze cierra acuerdo con Braulio y te empieza a dar una mano. No tuve novedades del acceso al FTP por ahora, pero mañana teóricamente vemos a la gente de Klaukol y se lo pido. Mientras tanto avancemos todo lo posible.

**Comment by FAAREIA** [comment]
Hola Lea, va bien. Hoy ya estoy terminando esta página: http://www.parexklaukol.com.ar/klaukol
Faltaría lo responsivo, pero el primer puntapie es el más largo porque hay que hacer el header y el footer también.

**Comment by LeandroBraier** [comment]
Genial. Seguí avanzando a paso firme con eso entonces, apenas está Braulio
para sumarse lo sumás así te da una mano con eso. Cualquier cosa que
necesites me avisás y apenas tenga el acceso al ftp te lo paso.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-02-25 12:04 GMT-03:00 Federico Arena notifications@github.com:
