### ISSUE TITLE
Mail de Respuesta a Participantes de #SerParte

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FranciscoLaPelicula#5]
Fede, cuando termines con la nueva landing, necesito que armes un HTML de mail como el de la respuesta automática de #SerParte que diga lo siguiente:

Subject: ¡Ya fueron elegidos los extras que participarán este lunes del rodaje de Francisco, la película!

Body: Hoy comunicaremos sus nombres en la página de Facebook de la peli. Para asegurarte de recibirlos, dale tu "me gusta" a la página en facebook.com/FranciscoLaPelicula (que la url sea en negrita y clickeable, obviamente)

Una vez más queremos agradecerte por participar de #SerParte, la convocatoria de extras para Francisco, la película. Te invitamos a seguir atento a próximas convocatorias y juegos.

Saludos!

**Comment by FAAREIA** [comment]
Hola Lea, ahi va el html, el subject lo pone Marce cuando hace el envío masivo:
http://benteveo.tv/_francisco/respuesta-ser-parte-anuncio.html

Abrazo

**Comment by LeandroBraier** [comment]
Buenísimo, Fede. Solo un cambio:

Cambiá la frase: "Hoy comunicaremos sus nombres en la página de Facebook de
la peli." por el siguiente: "Hoy comunicaremos los nombres de los
participantes elegidos para participar en la película a través de nuestra
página de Facebook."

Eso solo.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Fede avisame cuando ya no toques mas el template asi lo mando.
Lean: confirmame entonces que queres que salga hoy.

**Comment by FAAREIA** [comment]
Ahi ya esta listo: http://benteveo.tv/_francisco/respuesta-ser-parte-anuncio.html

**Comment by mkreyness** [comment]
Ok, Lean te mando un mail de prueba, decime si esta todo OK y lo largo 
para todos y todas.

**Comment by LeandroBraier** [comment]
Está todo más que perfecto, Marce. Larguemoslo nomás.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-02-20 17:07 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
listo, ya terminaron de salir.

**Comment by LeandroBraier** [comment]
Excelente Marce. Gracias!

**Comment by LeandroBraier** [comment]
Che, llegaron rebotes a info@franciscolapelicula pero también a
cuentas@benteveo.tv, puede ser?

Rarísimo. Lo chequeé y efectivamente son rebotes de la base de mails de la
peli.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-02-20 18:04 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Acordate que lo mande DESDE el server de benteveo.

Por lo tanto:
1) los rebotes a la cuenta de benteveo son porque el SERVIDOR BENTEVEO 
no pudo mandarlos (por ejemplo, porque pusieron servers erroneos)

2) los rebotes a la cuenta de info@francisco son de los SERVIDORES 
AJENOS, donde pudieron recibir los mails pero no pueden entregarlos a 
esos usuarios porque las casillas estan mal o estan over quota.

Seguramente si te fijas lo que dicen los rebotes es alusivo a esos dos 
tipos de problema.

**Comment by LeandroBraier** [comment]
Pero por qué le llegaron a cuentas@benteveo.tv específicamente? Los
enviaste desde ahí digamos?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-02-20 18:36 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
No es nada explicito (puse que los mandaba 
info@franciscolapelicula.com), pero tampoco puedo evitar el hecho de que 
el servidor ES benteveo.tv.
No es algo que le llegue a los destinatarios del mail, solo a los 
destinatarios del error (que no se pudo mandar el mail).

**Comment by LeandroBraier** [comment]
Entiendo Marce. Otra consulta: tenemos posibilidad de filtrar estos mails
con error dentro de la otra base?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-02-20 18:51 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Si me los pasas, los marco a mano. Son muchos ?

**Comment by LeandroBraier** [comment]
No te preocupes, a mano de última los marco yo. Son como 800 en cada mail,
raro no? Porque en total eran 1200.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-02-20 18:59 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
"A mano" no quiere decir que vaya uno por uno, digo que si me das la 
lista armo un query y los marco en la base.
Pero si son tantos entonces es otra cosa, no nos dejan mandar tantos 
mails juntos.
Mandame un ejemplo de cada rebote asi leo el motivo y vemos que hay que 
hacer.
Probablemente haya que remandarlos con un delay entre ellos.
Yo mande en tandas de a 100, y esperando un poco entre tanda y tanda.

**Comment by LeandroBraier** [comment]
Me suena más plausible lo que decís.

Veamos eso primero entonces.

Acá va el texto de rebote que llega a info@franciscolapelicula.com

This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  rocioaylenflores@gmail.com
    Domain benteveo.tv has exceeded the max emails per hour (326/300
(108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from localhost ([127.0.0.1]:49471 helo=django.duplika.com)
    by django.duplika.com with esmtp (Exim 4.84)
    (envelope-from cuentas@benteveo.tv)
    id 1YOu8o-001gCO-O3
    for rocioaylenflores@gmail.com; Fri, 20 Feb 2015 17:25:38 -0300
To: "rocio aylen flores zamorano"rocioaylenflores@gmail.com
From: "Francisco La Pelicula" info@franciscolapelicula.com
Subject:  ¡Ya fueron elegidos los extras que participarán este lunes
del rodaje de Francisco,  la película!
Date: Fri, 20 Feb 2015 17:25:38 -0300
X-Mailer: Perl script "mandamailfrancisco.pl"
    using Mail::Sender 0.8.22 by Jenda Krynicky, Czechlands
    running on django.duplika.com (72.52.188.252)
    under account "benteveo"
X-Mailer: use SimpleMood; - Sent via the email() function or easy()
method of Mail/Sender/Easy.pm and/or SimpleMood.pm both by Daniel
Muey.
X-Mailer: Sent via /home/benteveo/mk/mandamailfrancisco.pl
(mandamailfrancisco.pl) on django.duplika.com.com by uid 657
(benteveo) / euid 657 (benteveo) at 1424463938 (unix epoch)
Message-ID: 20150220_202538_058088.cuentas@benteveo.tv
MIME-Version: 1.0
Content-Type: multipart/mixed;
    boundary="Message-Boundary-by-Mail-Sender-1424463938"

This message is in MIME format. Since your mail reader does not understand
this format, some or all of this message may not be legible.

--Message-Boundary-by-Mail-Sender-1424463938
Content-Type: multipart/alternative;
boundary="Part-Message-Boundary-by-Mail-Sender-1424463938_2"

--Part-Message-Boundary-by-Mail-Sender-1424463938_2
Content-Type: text/plain
Content-Transfer-Encoding: 7BIT

Debe verse en HTML
--Part-Message-Boundary-by-Mail-Sender-1424463938_2
Content-Type: text/html
Content-Transfer-Encoding: 7BIT

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Francisco, Recen por m&iacute;</title>
</head>
<body>
    <div style="border: 1px solid #F6F6F6; margin: 0 auto; padding: 6px
20px 15px; width: 400px;">
        <table style="border-collapse: collapse; width: 100%;">
            <tbody>
                <tr>
                    <td bgcolor="#FFFFFF" style="border: 0; padding: 0; vertical-align: top;">
                        <div style="color: #56C5FF; font-family: Arial; font-size: 24px;
font-weight: 700; line-height: 60px;">&iexcl;Gracias por
participar!</div>
                        <div style="color: #444444; font-family: Arial; font-size: 14px;
font-weight: 400; line-height: 20px;">Hoy comunicaremos los nombres de
los participantes elegidos para participar en la pel&iacute;cula a
trav&eacute;s de nuestra p&aacute;gina de Facebook. Para asegurarte de
recibirlos, dale tu "me gusta" a la p&aacute;gina en <a
href="https://www.facebook.com/franciscolapelicula"
target="_blank">facebook.com/FranciscoLaPelicula</a></div>
                        <div style="color: #444444; font-family: Arial; font-size: 14px;
font-weight: 400; line-height: 20px; padding-top: 15px;">Una vez
m&aacute;s queremos agradecerte por participar de #SerParte, la
convocatoria de extras para Francisco, la pel&iacute;cula. Te
invitamos a seguir atento a pr&oacute;ximas convocatorias y
juegos.</div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <div style="border: 0; margin: 40px auto 20px; padding: 0 0 0 20px;
width: 420px;">
        <img src="http://franciscolapelicula.com/img/firma-email.png"
alt="Francisco, Recen por m&iacute;" style="border: 0; display:
block;" />
    </div>
</body>
</html

--Part-Message-Boundary-by-Mail-Sender-1424463938_2--
--Message-Boundary-by-Mail-Sender-1424463938--

_Acá va el texto de rebote que llega a cuentas@benteveo.tv
cuentas@benteveo.tv_

This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  paulareyno2000@hotmail.com
    SMTP error from remote mail server after RCPT
TO:paulareyno2000@hotmail.com:
    host mx3.hotmail.com [207.46.8.199]: 550 Requested action not taken:
    mailbox unavailable

------ This is a copy of the message, including all the headers. ------

Return-path: cuentas@benteveo.tv
Received: from localhost ([127.0.0.1]:49464 helo=django.duplika.com)
    by django.duplika.com with esmtp (Exim 4.84)
    (envelope-from cuentas@benteveo.tv)
    id 1YOu8o-001gBk-GY
    for paulareyno2000@hotmail.com; Fri, 20 Feb 2015 17:25:38 -0300
To: "paulina reyno"paulareyno2000@hotmail.com
From: "Francisco La Pelicula" info@franciscolapelicula.com
Subject:  =?UTF-8?B?wqFZYSBmdWVyb24gZWxlZ2lkb3MgbG9zIGV4dHJhcyBxdWUgcGFydGljaXBhcsOhbg==?=
=?UTF-8?B?IGVzdGUgbHVuZXMgZGVsIHJvZGFqZSBkZSBGcmFuY2lzY28=?=,
=?UTF-8?B?IGxhIHBlbMOtY3VsYSE=?=
Date: Fri, 20 Feb 2015 17:25:38 -0300
X-Mailer: Perl script "mandamailfrancisco.pl"
    using Mail::Sender 0.8.22 by Jenda Krynicky, Czechlands
    running on django.duplika.com (72.52.188.252)
    under account "benteveo"
X-Mailer: use SimpleMood; - Sent via the email() function or easy()
method of Mail/Sender/Easy.pm and/or SimpleMood.pm both by Daniel
Muey.
X-Mailer: Sent via /home/benteveo/mk/mandamailfrancisco.pl
(mandamailfrancisco.pl) on django.duplika.com.com by uid 657
(benteveo) / euid 657 (benteveo) at 1424463938 (unix epoch)
Message-ID: 20150220_202538_037712.cuentas@benteveo.tv
MIME-Version: 1.0
Content-Type: multipart/mixed;
    boundary="Message-Boundary-by-Mail-Sender-1424463938"

This message is in MIME format. Since your mail reader does not understand
this format, some or all of this message may not be legible.

--Message-Boundary-by-Mail-Sender-1424463938
Content-Type: multipart/alternative;
boundary="Part-Message-Boundary-by-Mail-Sender-1424463938_2"

--Part-Message-Boundary-by-Mail-Sender-1424463938_2
Content-Type: text/plain
Content-Transfer-Encoding: 7BIT

Debe verse en HTML
--Part-Message-Boundary-by-Mail-Sender-1424463938_2
Content-Type: text/html
Content-Transfer-Encoding: 7BIT

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Francisco, Recen por mí</title>
</head>
<body>
    <div style="border: 1px solid #F6F6F6; margin: 0 auto; padding: 6px
20px 15px; width: 400px;">
        <table style="border-collapse: collapse; width: 100%;">
            <tbody>
                <tr>
                    <td bgcolor="#FFFFFF" style="border: 0; padding: 0; vertical-align: top;">
                        <div style="color: #56C5FF; font-family: Arial; font-size: 24px;
font-weight: 700; line-height: 60px;">¡Gracias por participar!</div>
                        <div style="color: #444444; font-family: Arial; font-size: 14px;
font-weight: 400; line-height: 20px;">Hoy comunicaremos los nombres de
los participantes elegidos para participar en la película a través de
nuestra página de Facebook. Para asegurarte de recibirlos, dale tu "me
gusta" a la página en <a
href="https://www.facebook.com/franciscolapelicula"
target="_blank">facebook.com/FranciscoLaPelicula</a></div>
                        <div style="color: #444444; font-family: Arial; font-size: 14px;
font-weight: 400; line-height: 20px; padding-top: 15px;">Una vez más
queremos agradecerte por participar de #SerParte, la convocatoria de
extras para Francisco, la película. Te invitamos a seguir atento a
próximas convocatorias y juegos.</div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <div style="border: 0; margin: 40px auto 20px; padding: 0 0 0 20px;
width: 420px;">
        <img src="http://franciscolapelicula.com/img/firma-email.png"
alt="Francisco, Recen por mí" style="border: 0; display: block;" />
    </div>
</body>
</html

--Part-Message-Boundary-by-Mail-Sender-1424463938_2--
--Message-Boundary-by-Mail-Sender-1424463938--

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-02-20 19:28 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Y si, aca lo dice:

Domain benteveo.tv has exceeded the max emails per hour (326/300
(108%)) allowed. Message will be reattempted later

NO HAY QUE HACER NADA, dice que va a reintentar solo.
Lo que dice es que no nos dejan mandar mas de 300 mails por HORA.
