### ISSUE TITLE
Modificaciones Web Francisco

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FranciscoLaPelicula#6]
Fede, van unos cambios a hacer en la web de la peli. Todavía faltan cosas de ellos, la web no está para subir aun.

SECCIÓN INFO

Cambiar el póster por una imagen de la peli nueva que te adjunto por mail.

VERSIÓN MOBILE

Subir un "Loading" en gif animado y mensaje que bloquee modo vertical en mobile y ipad.

POP UPS DE FACEBOOK Y TWITTER

Con menos transparencia en las letras (TWITTER y FACEBOOK), para que pase un poco menos desapercibidas las ventanas.

ELENCO

Cambiar y agregar todas las fotos por las que te adjunto por mail:

Agregar a los siguientes personajes con sus fotos:

Jorge (cambiar la foto por la que te adjunto)

Ana (cambiar la foto por la que te adjunto)

Cecilia (cambiar la foto por la que te adjunto)

Regina (madre de Jorge): Laura Novoa 

Rosa (abuela de Jorge): Leonor Manso 

Jorge Joven: Gabriel Gallichio 

Luis (periodista de investigación): Alejandro Awada 

José (político): Jorge Marrale 

Eva (hija de Ana): Naia Guz Sanchez 

Cambiar el texto que lleva a twitter al siguiente: "Decile algo a Dario", "Decile algo a Silvia" etc

**Comment by FAAREIA** [comment]
Hola Lea, ahi van los cambios. Tengo que hacer unos ajustes aun, mañana por la mañana lo termino. Dale F5.

http://benteveo.tv/_francisco/info.html
http://benteveo.tv/_francisco/elenco.html (por ahora, para pasar los actores, arrastrá con el mouse hacia la izquierda)

Lo del mensaje en dispositivos que esten en vertical aún no esta.

Abrazo

**Comment by LeandroBraier** [comment]
Perfecto. Hoy te paso los datos de actores que faltan.

abrazo

**Comment by LeandroBraier** [comment]
Perdón, dos cambios más:
1. te pasé 3 fotos nuevas para Jorge, Ana y Cecilia pero sigo viendo las viejas.
2. Cambiar en "INFO" fecha de estreno para "Principios de 2016"

abrazo

**Comment by LeandroBraier** [comment]
Fede, van los datos que faltaban de los actores. No te olvides de cambiar las fotos de Jorge, Ana y Cecilia y el dato que te pedí cambiar en INFO.

Regina (madre de Jorge): 

Laura Novoa (Regina, madre de Jorge)
"CohenVsRosi", "La nube" y "Ay, Juancito", entre otras.

Leonor Manso (Rosa, abuela de Jorge)
"Made in Argentina", "La última siembra" y "El Santo de la Espada", entre otras.

Gabriel Gallichio (Jorge Joven)
"El tesoro del portugués" y "Sueña conmigo", entre otras.

Alejandro Awada (Luis)
"Nueve reinas", "El aura" y "Whisky Romeo Zulu", entre otras.

Jorge Marrale (José) 
"Cómplices", "Ay Juancito" y "Motivos para no enamorarse", entre otras.

Naia Guz Sanchez (Eva)
Debut cinematográfico de la joven actriz.

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, ahi esta todo. Dale F5.
Faltaría los datos de la actriz de regina.
Fijate de verlo en modo vertical también que ya esta el mensaje.

Abrazo!

**Comment by LeandroBraier** [comment]
Gracias Fede!

Estaban los datos. Son estos:

Laura Novoa (Regina, madre de Jorge)
"CohenVsRosi", "La nube" y "Ay, Juancito", entre otras.

Quizá se me repitió una linea más arriba, pero son esos.

abrazo

**Comment by FAAREIA** [comment]
Actualizado.

**Comment by LeandroBraier** [comment]
Fede, estaba repasando la web para una reunión mañana y encontré dos temitas:

1) Hay que sacar la sección de "Ser parte". Esto lo necesitaría cuanto antes. Al menos para la reunión de mañana a las 9am.

2) Tanto en la sección "Elenco" como en la sección "Fotos" los puntitos celestes no avanzan. Siempre queda como seleccionado el primero. Además las flechas no se destacan lo suficiente. Poneles un glow o algo para que sean más visible de primera mano.

abrazo

**Comment by FAAREIA** [comment]
1 Ya esta
2 En proceso!

**Comment by LeandroBraier** [comment]
Gracias Fede!

Excelente.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ahi esta el 2 punto. Lo que hice fue agrandar un poco los círculos y las flechas. Tené en cuenta que le puse que no rote solo asi no le rota al usuario cuando el quiere ir pasando. Se pasa con los circulos, con las flecha y hasta agarrando el bloque y tirando hacia la izquierda. ^^ son bastantes opciones.
