### ISSUE TITLE
Nuevas Modificaciones Web Francisco

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FranciscoLaPelicula#7]
Fede, te paso modificaciones para la web de Francisco. Pueden ser para el miércoles 29/4 sin problemas:
1. Cambiar el título de la peli Bergoglio. El Papa Francisco

La estética es la que ves en este posteo:

https://www.facebook.com/franciscolapelicula/photos/a.802681176506138.1073741848.748852721888984/802682003172722/?type=1&permPage=1

¿Cómo se escribe?

Primera línea: Bergoglio (Tipografía : Swiss 721 Bold Condensed, 80%)
Segunda línea o subtítulo: El Papa Francisco (Tipografía: Gotham Regular)
1. Cambiar la música a una más épica, no tan religiosa.

Bajate este track de prueba de Audio Jungle y ponelo. En la entrega vemos si les gusta y lo compramos.

http://audiojungle.net/item/epic-movie-trailer/6009753
1. Cambiar donde dice "Elenco" debe decir "Equipo" y sumar en esa sección 3 integrantes:

Beda Docampo Feijóo, Guión y Dirección. Con esta foto: https://drive.google.com/folderview?id=0B_kxBPQ4ZykDNVlqSUllbTRnSk0&usp=sharing&tid=0B_kxBPQ4ZykDY0xUa2JZd0xOSWM

Pablo Bossi, Productor. Con esta foto: http://www.lasrosasonline.com/arc_up/revistas_notas/358_4d9a2ef93838e.jpg

Kiko de la Rica, Director de Fotografía. Con esta foto: 

https://drive.google.com/folderview?id=0B_kxBPQ4ZykDSTEwT3M5V0NodzA&usp=sharing&tid=0B_kxBPQ4ZykDY0xUa2JZd0xOSWM
1. El Loop de video va a cambiar. Te lo va a mandar Eze cuando esté listo.
2. Quitar sección trailer hasta que esté listo.
3. Quitar la pestaña "Libro" por el momento.
4. Vamos a agregar una sección de "Contacto" con datos de las productoras y agentes de prensa. Eze te va a enviar esos datos entre mañana y pasado. 

abrazo

**Comment by LeandroBraier** [comment]
Fede, en qué estamos con este tema?

Te actualizo los cambios necesarios, los cuales necesitaríamos tener listos para mañana a la tarde de ser posible.
1. Cambiar el título de la peli Bergoglio. El Papa Francisco
   La estética es la que ves en este posteo:

https://www.facebook.com/franciscolapelicula/photos/a.802681176506138.1073741848.748852721888984/802682003172722/?type=1&permPage=1

¿Cómo se escribe?

Primera línea: Bergoglio (Tipografía : Swiss 721 Bold Condensed, 80%)
Segunda línea o subtítulo: El Papa Francisco (Tipografía: Gotham Regular)

Te subí el logo vectorizado y con todo detalle a la carpeta BENTEVEO MAQUETADOR/BERGOGLIO
1. Cambiar la música a una más épica, no tan religiosa.

Bajate este track de prueba de Audio Jungle y ponelo. En la entrega vemos si les gusta y lo compramos.

http://audiojungle.net/item/epic-movie-trailer/6009753
1. Cambiar donde dice "Elenco" debe decir "Equipo" y sumar en esa sección 3 integrantes:
   Beda Docampo Feijóo, Guión y Dirección. Con esta foto: https://drive.google.com/folderview?id=0B_kxBPQ4ZykDNVlqSUllbTRnSk0&usp=sharing&tid=0B_kxBPQ4ZykDY0xUa2JZd0xOSWM

Pablo Bossi, Productor. Con esta foto: http://www.lasrosasonline.com/arc_up/revistas_notas/358_4d9a2ef93838e.jpg

Kiko de la Rica, Director de Fotografía. Con esta foto:

https://drive.google.com/folderview?id=0B_kxBPQ4ZykDSTEwT3M5V0NodzA&usp=sharing&tid=0B_kxBPQ4ZykDY0xUa2JZd0xOSWM
1. El Loop de video de fondo cambia. Descargatelo de acá y bajalo nomás:

https://www.wetransfer.com/downloads/4a1bdef628c14aa5629bf500f4a1fb4620150518213047/6a7bd0d26c3c5cd49cb789652928b5c120150518213047/8a3703
1. Quitar sección trailer hasta que esté listo.
2. Quitar la pestaña "Libro" por el momento.
3. Agregar una sección de Contacto de prensa. La sección se llama "Prensa"

Debe tener un formulario que pida: Nombre, Apellido, Email, Medio u organización y Mensaje

Debe llevar al mail prensa@franciscolapelicula.com (el cual debemos crear en el mismo servidor de la peli)

Debajo del Formulario debe estar el siguiente texto:

Prensa de la película

prensa@franciscolapelicula.com

Confirmame porfa si recibiste todo esto y lo podremos tener para mañana a la tarde o a más tardar jueves a la mañana.

abrazo

**Comment by FAAREIA** [comment]
Llegamos Lea, para el jueves seguro. Para mañana puede ser.

**Comment by LeandroBraier** [comment]
Genial Fede!

Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-05-19 12:06 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Lea, el video me lo tendrían que pasar con el audio incrustado. No puedo ponerle un audio por fuera y loopearlo justo con el video en sincro.
Gracias.

**Comment by LeandroBraier** [comment]
No problem. Ahora te lo mando por WeTransfer.

abrazo

**Comment by LeandroBraier** [comment]
Se está enviando. Confirmame cuando lo recibas porfa.
abrazo

**Comment by FAAREIA** [comment]
Fijate ahi Lea:
http://www.benteveo.tv/_francisco/index.html

**Comment by LeandroBraier** [comment]
Está muy bien. Te paso feedback:

1) En el título falta destacarlo con sombra y agregar debajo "Próximamente
en cines" en Gotham. [x]

2) El video de fondo se ve más comprimido que la versión anterior. Fijate
si podés mejorar la compresión, utilizando la misma que teníamos antes está
OK. Además, quitale al principio del video la leyenda con el título
anterior. Que solo se vean imágenes, no el título de la peli (dentro del
video mismo estoy hablando) [x]

3) En la Home me habías dicho que el embed de tweets no se puede alargar un
poco más para que no sea necesario scrollear no? Sería lo ideal. Si podés
hacelo.

4) En Equipo primero de todo deben figurar Grandinetti, Silvia y Leticia.
El director, productor y DF pasan a la segunda página. [x]

5) En Prensa me aparece una página vieja, no el formulario y datos que te
pedí ahora. Además, queda iluminado de azul Galería, no Prensa.
 En Galería seguramente te pase más fotos para subir más adelante. Hay un
CMS donde las pueda cargar o es manual? Decime como preferís hacer. [x]

6) Para editar la URL de YouTube necesitamos el mismo trabajo que precisamos para Parex por parte tuya 
Instructivo:
https://support.google.com/youtube/answer/2657968?ref_topic=3024172&hl=es ESPERANDO SUBSCRIPTORES

El acceso al canal de youtube es:

parexklaukolarg@gmail.com
pass: la misma que en deposit

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Sumo un Punto 6 en el thread anterior.

**Comment by FAAREIA** [comment]
1 - Título: Hecho
2 - Video: Hecho. Fijate si esta todo OK, no entendí la última parte.
3 - Tweets home: Hecho, de 240 a 320 lo pasé.
4 - Equipo: Hecho
5 - Prensa: Hecho
6 - Necesitamos 500 suscriptos para hacerlo. Fijate el segundo título: "Requisitos de idoneidad"

**Comment by FAAREIA** [comment]
Lo de la galería se mete a mano. No hay CMS.

**Comment by LeandroBraier** [comment]
Entiendo. Puse una X a los puntos hechos. Nos quedarían:

5- Prensa: Falta el texto que te pedí debajo:

Prensa de la película
prensa@franciscolapelicula.com

Además necesitaría acceso a ese mail o que me hagas un forward a mi mail desde ese mail para poder testear el formulario.

abrazo

**Comment by FAAREIA** [comment]
Ahi ya lo actualicé Lea. también le puse el forward

**Comment by LeandroBraier** [comment]
En la parte de PRENSA yo sigo sin ver la línea que te pedía. Puede ser?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Estoy viendo que el mail que me llega desde el formulario es porque yo
escribí en el mismo. Si yo escribí en el formulario no me debería llegar
ningún mail de "Ya estás participando". Directamente no debería llegarme
nada y que la gente de prensa responda directamente desde su mail.

A su vez, no me llegó ningún forward del contenido del formulario.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Me había llegado a Spam el Forward. Ok entonces. Simplemente quitemos el
mensaje automático que le llega al usuario.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-05-22 12:08 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

**Comment by LeandroBraier** [comment]
Fede, te estás olvidando de agregarle el desarrollado por Benteveo a los
sitios. Agregaselo a esta web de Francisco también por favor.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-05-22 12:20 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

> Me había llegado a Spam el Forward. Ok entonces. Simplemente quitemos el
> mensaje automático que le llega al usuario.
> 
> abrazo
> 
> Leandro Braier
> Producción Audiovisual & Social Media
> Benteveo Producciones http://benteveo.tv
> Móvil 1158717399
> 
> 2015-05-22 12:08 GMT-03:00 Leandro Braier leandrobraier@gmail.com:
> 
> Estoy viendo que el mail que me llega desde el formulario es porque yo
> 
> > escribí en el mismo. Si yo escribí en el formulario no me debería llegar
> > ningún mail de "Ya estás participando". Directamente no debería llegarme
> > nada y que la gente de prensa responda directamente desde su mail.
> > 
> > A su vez, no me llegó ningún forward del contenido del formulario.
> > 
> > Leandro Braier
> > Producción Audiovisual & Social Media
> > Benteveo Producciones http://benteveo.tv
> > Móvil 1158717399
> > 
> > On Fri, May 22, 2015 at 12:03 PM, Leandro Braier <leandrobraier@gmail.com
> > 
> > > wrote:
> > > 
> > > En la parte de PRENSA yo sigo sin ver la línea que te pedía. Puede ser?
> > > 
> > > Leandro Braier
> > > Producción Audiovisual & Social Media
> > > Benteveo Producciones http://benteveo.tv
> > > Móvil 1158717399
> > > 
> > > On Thu, May 21, 2015 at 3:21 PM, Federico Arena <

**Comment by LeandroBraier** [comment]
Un tema más. Está responsive?

Mirá como se ve en Safari del iPhone 6.

![captura safari iphone 6](https://cloud.githubusercontent.com/assets/6719872/7776451/72eb7bbc-0091-11e5-9b11-e14b41bf824d.png)

**Comment by FAAREIA** [comment]
Si esta responsive, ahi ajusto eso. Tené en cuenta también que cuando haya cambios, hay cosas que pueden faltar ajustar.

Lo de la línea de prensa, no se bien a que te referis. Ahora ajusto lo del mailing de prensa.

**Comment by FAAREIA** [comment]
El desarrollado por benteveo esta en el footer Lea, a lo último.

**Comment by LeandroBraier** [comment]
No lo habia visto. Perdón.

Lo de la linea es lo siguiente:

Prensa de la película
prensa@franciscolapelicula.com

**Comment by FAAREIA** [comment]
Lo del menú ya lo corregí, dale F5.
Lo del email, yo creo que no hace falta porque esta el formulario que va ahi mismo, a prensa@
El tema también de dejar el mail "abierto" es que te pueden llegar 1500 mails basura/al-pedo demás.

**Comment by FAAREIA** [comment]
Fijate que lo de prensa ya tiene que estar bien

**Comment by LeandroBraier** [comment]
Gracias Fede. Lo veo bien en Versión Mobile. Pero de todas formas cuando
tarda en cargar el video aparecer el primer fotograma del video, que justo
tiene el logo de la peli. Con lo cual se ve repetido el logo dos veces.
Quitá ese fotograma. Que el primer fotograma del video sea el actor
caminando, así por lo menos de fondo queda algo más lindo para el que tiene
internet lento.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Hecho, ahi le puse lo primero que aparece en el video

**Comment by LeandroBraier** [comment]
Perfecto, Fede. Cierro este ticket y te paso más modificaciones que me pidieron.

abrazo
