### ISSUE TITLE
FTP para envio de materiales desde España

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FranciscoLaPelicula#8]
Marce, tenemos un FTP para pasarle a la gente de España y que nos suban ahí archivos de video bastante pesados?

Necesitamos eso.

Si entra en el servidor de Benteveo genial. Confirmame nomás y pasame los datos de acceso al FTP para pasarles.

abrazo

**Comment by FAAREIA** [comment]
No usaría el FTP de Benteveo. Es uno común y corriente. Los otros host grandes que quedan no son nuestros sino de Dánica o Parex y evitaría que el cliente suba GBs en video a esos servidores.
Les diría que usen WeTransfer o Dropbox
