### ISSUE TITLE
Modificaciones FInales Web Francisco. 27/05

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FranciscoLaPelicula#9]
Fede, van nuevas modificaciones para el sitio. 

1) En Sección Info, cambiar la foto de Grandinetti por el póster que aparece acá:

http://www.pampafilms.com.ar/Site/index.php/es/lanzamientos/francisco-la-pelicula

2) En Sección Info cambiar lanzamiento 2016 por Lanzamiento Septiembre 2015. 

3) En el ultimo parrafo dice "en rodaje desde... " poné "Se rodó en locaciones de Buenos Aires, Roma y Madrid. Ahora, en post producción. Estreno Septiembre 2015"

4) En sección "EQUIPO" quitemos a Pablo Bossi, Beda Docampo y Kiko de la Rica y pongamoslos en una nueva sección llamada Equipo. A la antigua sección Equipo, donde solo quedan actores, cambiarle el nombre nuevamente a "Elenco".

Agrégale a Pablo Bossi el texto debajo que dice las películas: "Nueve Reinas, El Hijo de la Novia y Un Cuento Chino, entre otras"

Agrégale a Beda Docampo Feijoo el texto "Los amores de Kafka, El marido perfecto y Buenos Aires me mata, entre otras"

Agrégale a Kiko de la Rica "Lucía y el sexo, Los crímenes de Oxford, Balada triste de trompeta, entre otras." 

4)En la GALERIA de fotos, te paso  links de drive de donde descargarte más fotos para agregar. SI no podés acceder a alguna avisame:

https://lh5.googleusercontent.com/uy9yxRR2A4ikW7fvQZ7gvMioE6qCmPP0s_9XYmy5owNV9WUxtkZaQnwGGeRIrGXmWHGhGg=w2560-h1020

https://lh5.googleusercontent.com/vX3ae33T_nyXG8rVuJ08ixFbHt7r3YPNpTNc7NvPZGkvE1ZXl1n6LyMoG6pSqHw2k2GrbQ=w2560-h1020

https://lh6.googleusercontent.com/1l2Sk-k2RwA6FQTQr5VMFCNxeLVSHIuZDJ4B8FaujLdN8mBSqifqZR33DBxomMdpzz7sNQ=w2560-h1020

https://lh4.googleusercontent.com/zQAHrT6C_tYxL35ogEQJjTlogSEdcy88VtvcZcuLKU_7ccwyst5FDOmr5WKJVUlh6BSwbw=w2560-h1020

https://lh4.googleusercontent.com/kfHwOk3LinXve6-4ureXc3k2z4kztV9kv--3b3WOWqbuXXUK9OtqxH2SbPSPmQhRgjtJFA=w2560-h1020

https://lh6.googleusercontent.com/lyNMxRzHdLjtg8qvOOFLHiyN90r0qcU6MVc7vtiQzp6rWoE6yPlnUt2w5jMrLikx6MK14g=w2560-h1020

https://lh3.googleusercontent.com/fT2ec8trgkwR-NjkpoJQP3XAcCOcYKyg7IcWV1zdchaoUJfxtyKqbSMUcArsZ2uDwqkm0g=w2560-h948

https://lh3.googleusercontent.com/z6z0a3VOqrXNTKacIY1lQRcRmQOL56ZUR0ohv8xszrI5Y48DMWsykPla856TdRld-IabgA=w2560-h1020

https://lh5.googleusercontent.com/9sjMWEa1AoxCi14Zk99w-tmtkqmWNhNebUlOlI5Uff5Pzk0Bs8pikFb_Stz4BZRlDXkmbQ=w2560-h1020

https://lh4.googleusercontent.com/9zldmcDxrX5ZmlnHDhakCUoEnZYDESim-kqqOw6O_qvLalgOWGY-6rmU2ggNLat-zQaofw=w2560-h948

https://lh4.googleusercontent.com/fK836h3kBgRqAulevAAsEf5hfoWeFzeFUluWvZPwh00Z7bcSwakHHlR5Q_LpTd-8G3TEmA=w2560-h1020

https://lh6.googleusercontent.com/OJeKqrCCLcUw_Eb66OqPHdOEvQFC9QLqIfn3r8lSVFfQ2dWpkU9_vU913AIUbkCGJrzfZA=w2560-h1020

5) En el footer, donde dice "PAMPA FILMS" que haya un link que lleve a:

http://www.pampafilms.com.ar/

abrazo

**Comment by LeandroBraier** [comment]
Fede, hoy tenemos que ir avanzando con esto también. Te sumo cambios editados en la entrada anterior. Está todo acá. abrazo

**Comment by braulio-evangelisti** [comment]
Hola Lea

Solamente donde dice "Pampa Films" o el link abarcaría "Pampa Films-Gloriamundi" ?

**Comment by LeandroBraier** [comment]
Que abarque todo por ahora.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by braulio-evangelisti** [comment]
Listo Lea. 

Ya están aplicados y subido los cambios.

**Comment by LeandroBraier** [comment]
Excelente Braulio. Gracias!
